### PR TITLE
Use USA style date time when adding/editing events

### PR DESCRIPTION
**Pull request by mrrsm**
The datepicker seems to want to use the format "MM/DD/YYYY HH/MM PP".
I changed the php to format the date like that for adding and editing events.

### CODE REVIEW

**Comment by mrrsm** [comment]
This should fix #132

**Comment by GrahamCampbell** [comment]
Can you standardise it all to UK format please?

**Comment by mrrsm** [comment]
I'm not really sure what version of the bootstrap-datetimepicker this is using.  It appears that this method works though for setting the format.

**Comment by GrahamCampbell** [comment]
Thank you. :)

**Pull request merged**
