### PR TITLE
bugfix: fix edit page form and edit post form

### PR DESCRIPTION
**Pull request by xcaptain**
On my site, update a page nothing happens and
update a post will cause an error.
use method="POST" and method="PATCH" to perform a patch operation
fixed that problem

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why have method and _method?

**Comment by xcaptain** [comment]
@GrahamCampbell According to http://laravel.com/docs/5.1/routing#form-method-spoofing , to perform a  patch request, must use _method="PATCH"

**Comment by GrahamCampbell** [comment]
You don;t have to. Just send an ACTUAL patch request instead of a post request with the _method set surely?

**Comment by GrahamCampbell** [comment]
Instead of spoofing it as the link shows.

**Comment by xcaptain** [comment]
I tested this with Chromium 45, when I update a post or a page, I can't see a post request with the inspector and nothing changed. So I think this is a bug.

**Comment by GrahamCampbell** [comment]
Meh, well if this works, I might as well merge it. Thanks. :)

**Pull request merged**
